#!/usr/bin/env python
# -*- coding: utf-8 -*-

from libnmap.parser import NmapParser

rep = NmapParser.parse_fromfile("/Users/mborowski/Projects/red_team/parser/scan_prev.xml")     #change this 

for _host in rep.hosts:
    if _host.is_up():
        # get CPE from service if available
        for s in _host.services:
            print(
            "Service: {0}/{1} ({2})".format(
                    s.port, s.protocol, s.state
                )
            )
            print(
            "   Host: {0} {1}".format(_host.address, " ".join(_host.hostnames))
            )
            # NmapService.cpelist returns an array of CPE objects
            #for _serv_cpe in s.cpelist:
            #    print("        CPE: {0}".format(_serv_cpe.cpestring))

               

