apiVersion: v1
kind: Service
metadata:
  name: semgrep-service
spec:
  selector:
    app: semgrep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Assuming Semgrep is listening on 8080
  type: ClusterIP  # Or use NodePort, LoadBalancer based on requirement